IMAGE_NAME = "bento/debian-12"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
	v.customize ["modifyvm", :id, "--intnet1", "intnet"]
    end

    config.vm.define "debian" do |debian|
        debian.vm.box = IMAGE_NAME
        debian.vm.hostname = "debian"

        # Nastavení vnitřní sítě s názvem intnet
	debian.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "intnet", auto_config: false
    end
end